apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: reboot-agent
spec:
  template:
    metadata:
      labels:
        name: reboot-agent
    spec:
      containers:
      - name: reboot-agent
        image: gcr.io/convoy-adapter/reboot-agent:latest
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
